"""Interactive Live Demonstration of the Autonomous Security Research Agent.

This script demonstrates step-by-step:
1. Parsing a bug bounty program profile (YAML + checkboxes + headers).
2. Enforcing deterministic scope boundaries (Allowed vs Blocked).
3. Mandatory HackerOne header injection.
4. Dynamic Scope Modification at runtime (adding/removing rules).
5. Generating reports and cryptographic evidence manifests.
"""

import asyncio
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich import box

from src.core.engine import OrchestrationEngine
from src.policy.profile_parser import ProfileParser
from src.policy.scope_manager import DynamicScopeManager
from src.models.enums import RiskLevel, ScopeRuleType, ScopeEffect, FindingSeverity
from src.tools.http_adapter import HttpToolAdapter
from src.tools.dns_adapter import DnsToolAdapter
from src.tools.probing_adapter import HttpProbingAdapter

console = Console()

# 1. Standard YAML target profile (as generated by ChatGPT prompt)
TARGET_YAML = """
program_metadata:
  program_name: "FinTech Corp Bug Bounty Program"
  target_summary: "Production Web Applications and API Perimeter"
  authorization_reference: "H1-AUTH-FINTECH-2026-X9"
  researcher_handle: "almoatasem_bellah"
  authorization_reference: "AUTH-DEMO-2026-001"

network_and_headers:
  rate_limit_rps: 5
  mandatory_headers:
    X-HackerOne-Research: "almoatasem_bellah"
    X-Security-Scan: "Authorized-Audit"
  rate_limit_rps: 5

scope_definition:
  in_scope:
    - type: DOMAIN
      pattern: "*.fintech-demo.com"
      notes: "Main web applications and subdomains"
    - type: DOMAIN
      pattern: "example.com"
      notes: "Public sandbox testbed"
  out_of_scope:
    - type: DOMAIN
      pattern: "payments.fintech-demo.com"
      notes: "Third-party payment processor - STRICTLY FORBIDDEN"

rule_checkboxes:
  prohibit_dos_attacks: true
  prohibit_destructive_writes: true
  prohibit_credential_bruteforce: true
  prohibit_social_engineering: true
  prohibit_third_party_testing: true
"""


async def main():
    console.print(Panel.fit(
        "[bold cyan]Autonomous Security Research Agent — Live Demonstration[/bold cyan]\n"
        "[dim]Showing Scope Engine, Dynamic Rules, Header Injection & Report Generation[/dim]",
        border_style="cyan"
    ))

    # --- STEP 1: Parse YAML Profile ---
    console.print("\n[bold yellow]Step 1: Parsing Imported Target Profile (ProfileParser)[/bold yellow]")
    parsed = ProfileParser.parse_yaml(TARGET_YAML)
    console.print(f"  [green][+][/green] Target Name: [bold]{parsed.engagement.name}[/bold]")
    console.print(f"  [green][+][/green] Researcher: [bold]{parsed.engagement.researcher_identity}[/bold]")
    console.print(f"  [green][+][/green] Mandatory Headers: [cyan]{parsed.policy.required_headers}[/cyan]")
    console.print(f"  [green][+][/green] Checkboxes Loaded:")
    for rule, val in parsed.rule_checkboxes.items():
        status_icon = "[green]ACTIVE[/green]" if val else "[red]DISABLED[/red]"
        console.print(f"      - {rule}: {status_icon}")

    # --- STEP 2: Initialize Engine ---
    console.print("\n[bold yellow]Step 2: Initializing Agent Engine & Scope Rules[/bold yellow]")
    engine = OrchestrationEngine(base_data_dir="data/engagements")
    engine.tool_registry.register(HttpToolAdapter())
    engine.tool_registry.register(DnsToolAdapter())
    engine.tool_registry.register(HttpProbingAdapter())

    engagement = engine.initialize_engagement(
        name=parsed.engagement.name,
        target_summary=parsed.engagement.target_summary,
        authorization_ref=parsed.engagement.authorization_ref,
        researcher_identity=parsed.engagement.researcher_identity,
        rate_limit_rps=parsed.engagement.rate_limit_rps
    )
    engine.load_scope_and_policy(parsed.scope_rules, parsed.policy)
    preflight = engine.run_preflight_checks()
    console.print(f"  [green][+][/green] Engagement ID: [bold]{engagement.id}[/bold]")
    console.print(f"  [green][+][/green] Preflight Status: [bold green]{preflight['status']}[/bold green]")
    console.print(f"  [green][+][/green] State: [bold]{engine.state_machine.current_state.value}[/bold]")

    # --- STEP 3: Test Scope Engine Guardrails ---
    console.print("\n[bold yellow]Step 3: Testing Scope Engine Guardrails (Allowed vs Blocked)[/bold yellow]")
    test_targets = [
        ("api.fintech-demo.com", "Subdomain in-scope (*.fintech-demo.com)"),
        ("payments.fintech-demo.com", "Explicitly excluded out-of-scope target"),
        ("google.com", "Completely unlisted external target (Default-Deny)")
    ]

    scope_table = Table(title="Scope Evaluation Results", box=box.SIMPLE_HEAVY)
    scope_table.add_column("Target URL / Host", style="cyan")
    scope_table.add_column("Rule Match Description", style="dim")
    scope_table.add_column("Scope Status", style="bold")

    for target_host, desc in test_targets:
        eval_res = engine.scope_engine.evaluate(target_host)
        status_badge = "[bold green][PASS] IN-SCOPE[/bold green]" if eval_res.is_allowed else "[bold red][BLOCK] OUT-OF-SCOPE[/bold red]"
        scope_table.add_row(target_host, desc, status_badge)

    console.print(scope_table)

    # --- STEP 4: Action Gate & Header Injection ---
    console.print("\n[bold yellow]Step 4: Action Gate Verification & Automatic Header Injection[/bold yellow]")
    
    # Test A: Allowed Action on in-scope endpoint
    gate_allowed = engine.action_gate.validate_action(
        target="https://api.fintech-demo.com/user/profile",
        action_name="differential_audit",
        risk_level=RiskLevel.LOW
    )
    console.print(f"  [green][+][/green] Action 'differential_audit' on in-scope target:")
    console.print(f"      Passed Gate: [bold green]{gate_allowed.passed}[/bold green]")
    console.print(f"      Injected Headers: [cyan]{gate_allowed.injected_headers}[/cyan]")

    # Test B: Forbidden Action (DoS / stress test)
    gate_blocked = engine.action_gate.validate_action(
        target="https://api.fintech-demo.com/login",
        action_name="dos",
        risk_level=RiskLevel.CRITICAL
    )
    console.print(f"  [red][-][/red] Action 'dos' on target:")
    console.print(f"      Passed Gate: [bold red]{gate_blocked.passed}[/bold red]")
    console.print(f"      Rejection Reason: [yellow]{gate_blocked.rejection_reason}[/yellow]")

    # --- STEP 5: Dynamic Scope Modification ---
    console.print("\n[bold yellow]Step 5: Dynamic Scope Modification at Runtime[/bold yellow]")
    scope_mgr = DynamicScopeManager(engine.db_manager, engine.scope_engine, engagement.id)
    
    # Check new target before adding
    new_domain = "partner-portal.fintech-demo.com"
    before_eval = engine.scope_engine.evaluate(new_domain)
    console.print(f"  [cyan]>[/cyan] Evaluating '{new_domain}' before adding: Allowed = {before_eval.is_allowed}")

    # Now let's say user wants to EXCLUDE partner-portal at runtime
    console.print(f"  [cyan]>[/cyan] Adding runtime EXCLUSION rule for '{new_domain}'...")
    new_rule = scope_mgr.add_rule(
        pattern=new_domain,
        rule_type=ScopeRuleType.DOMAIN,
        effect=ScopeEffect.EXCLUDE,
        priority=60,
        notes="Dynamically excluded at runtime by researcher"
    )
    after_eval = engine.scope_engine.evaluate(new_domain)
    console.print(f"  [green][+][/green] Dynamic Rule Added! ID: {new_rule.id}")
    console.print(f"  [green][+][/green] Evaluating '{new_domain}' after exclusion rule: Allowed = [bold red]{after_eval.is_allowed}[/bold red] ({after_eval.reason})")

    # --- STEP 6: Deliverables & Report Generation ---
    console.print("\n[bold yellow]Step 6: Generating Deliverables & Cryptographic Manifests[/bold yellow]")
    deliverables = engine.generate_deliverables()
    
    deliv_table = Table(title="Generated Assessment Deliverables", box=box.ROUNDED)
    deliv_table.add_column("Report Type", style="cyan")
    deliv_table.add_column("Saved File Path", style="dim")
    deliv_table.add_column("Status", style="bold green")

    for name, path in deliverables.items():
        deliv_table.add_row(name.replace("_", " ").title(), str(path), "CREATED")

    console.print(deliv_table)
    console.print("\n[bold green][SUCCESS] Demonstration Completed Successfully![/bold green]\n")


if __name__ == "__main__":
    asyncio.run(main())
